In [1]:
import sqlite3
import pandas as pd
import requests

In [2]:
conn = sqlite3.connect("community_solar.db")
cursor = conn.cursor()

In [3]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('sqlite_sequence',), ('LOCATIONS',), ('NONPROFITS',), ('GOOGLE_SOLAR',)]

# Load Data

In [4]:
locations_query = "SELECT * FROM LOCATIONS WHERE dlgf_prop_class_code LIKE '6%'"
df_locations = pd.read_sql_query(locations_query, conn)
df_locations

,location_id,X,Y,objectid,add_full,addnum_pre,add_number,addnum_suf,st_premod,st_predir,...,geostreettype,geounit,geocity,geozip,geostate,geobg10,geobg20,geocounty,geosufdir,user_fld
0,54,-84.927791301,40.8314136170001,54,216 N FIFTH ST,,216.0,,,NORTH,...,ST,,DECATUR,46733,IN,180010303003.0,180010303003.0,ADAMS,,ADAMS;18001;180010303003;180010303003;01050320...
1,85,-84.948219493,40.668662897,85,,,1200.0,,,,...,RD,,DECATUR,46711,IN,180010306002.0,180010306002.0,ADAMS,,ADAMS;18001;180010306002;180010306002;01083310...
2,96,-84.9552047889999,40.7444441800001,96,,,30.0,,,,...,,,DECATUR,46772,IN,180010305001.0,180010305001.0,ADAMS,,ADAMS;18001;180010305001;180010305001;01080410...
3,97,-84.959462569,40.5901470150001,97,,,225.0,,,,...,ST,,DECATUR,46740,IN,180010307004.0,180010307004.0,ADAMS,,ADAMS;18001;180010307004;180010307004;01112940...
4,126,-84.9450544969999,40.8285533660001,126,1828 W MONROE ST,,1828.0,,,WEST,...,ST,,DECATUR,46733,IN,180010302002.0,180010302002.0,ADAMS,,ADAMS;18001;180010302002;180010302002;01050420...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93361,3291004,-86.625296197,39.2393445750001,3291004,6151 N MATTHEWS DR UNIT 410,,6151.0,,,NORTH,...,DR,UNIT 410,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE,,MONROE;18105;181050013031;181050013031;5304033...
93362,3291005,-86.625296197,39.2393445750001,3291005,6151 N MATTHEWS DR UNIT 411,,6151.0,,,NORTH,...,DR,UNIT 411,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE,,MONROE;18105;181050013031;181050013031;5304033...
93363,3291287,-86.617589653,39.2274599340001,3291287,4616 N CAMPBELL PARK RD,,4616.0,,,NORTH,...,RD,,ELLETTSVILLE,47429,IN,181050013043.0,181050013043.0,MONROE,,MONROE;18105;181050013043;181050013043;5304104...
93364,3291288,-86.614138372,39.224631903,3291288,4586 N HARTSTRAIT RD,,4586.0,,,NORTH,...,RD,,ELLETTSVILLE,47429,IN,181050013043.0,181050013051.0,MONROE,,MONROE;18105;181050013043;181050013051;5304104...
93365,3291335,-86.633661488,39.222255332,3291335,4810 N ANGELA WAY,,4810.0,,,NORTH,...,WAY,,BLOOMINGTON,47404,IN,181050013041.0,181050013041.0,MONROE,,MONROE;18105;181050013041;181050013041;5304161...

In [5]:
nonprofits_query = "SELECT * FROM NONPROFITS WHERE source_agency == 'SOS'"
df_nonprofits = pd.read_sql_query(nonprofits_query, conn)
df_nonprofits

,comp_name,address1,CITY,ZIP,contact_name,source_agency,county
0,"Ac Football Booster Club, Inc. ()",113 N 2Nd St,Decatur,46733,,SOS,Adams
1,Adams Central Character Academy Inc (),Po Box 121,Monroe,46772,,SOS,Adams
2,Adams Central Elementary School Building Corpo...,C/O Audra S. Snyder,Decatur,46733,Steve Stucky,SOS,Adams
3,"Adams Central Flag Football League, Inc. ()",3202 N. 700 E.,Decatur,46733,,SOS,Adams
4,"Adams Central Golf Booster Club, Inc ()",235 Harvest Ln,Monroe,46772,,SOS,Adams
...,...,...,...,...,...,...,...
40029,"Wild At Heart Wildlife Rehab, Inc. ()",408 Arrowhead Ct,Columbia City,46725,,SOS,Whitley
40030,"Wildcat Booster Club, Inc. ()",1 Big Blue Avenue,South Whitley,46787,,SOS,Whitley
40031,"Wishbone Orthopaedic Foundation, Inc. ()",1560 North State Road 5,Larwill,46764,,SOS,Whitley
40032,"World Wagyu Council, Inc. ()",6755 East 900 North,Columbia City,46725,,SOS,Whitley
40033,"Worship 995 Ministries, Inc. ()",8901 Mccomb Rd,Churubusco,46723,,SOS,Whitley

In [6]:
google_solar_query = "SELECT * FROM GOOGLE_SOLAR"
df_google_solar = pd.read_sql_query(google_solar_query, conn)
df_google_solar

,solar_id,location_id,latitude,longitude,max_panel_count,yearly_energy_production,date_added
0,1,26769,41.018635,-85.167521,53,20784.182,2025-04-06 02:29:54

# Analyze Data

## Raw Analysis

In [7]:
df_locations["dlgf_prop_class_code"].value_counts()

dlgf_prop_class_code
640    19081
680    14273
685    12047
699    11159
686     9147
610     5103
620     4226
650     4125
645     4005
670     3595
630     2031
690     1183
600     1116
660      872
661      404
669      359
665      340
662      265
622       35
Name: count, dtype: int64

In [15]:
for col in df_locations:
    print(col)
    nan_count = df_locations[col].isna().sum()
    empty_string_count = (df_locations[col] == "").sum() if df_locations[col].dtype == "object" else 0
    print(f"NaNs: {nan_count}, Empty strings: {empty_string_count}")
    print()

location_id
NaNs: 0, Empty strings: 0

X
NaNs: 0, Empty strings: 0

Y
NaNs: 0, Empty strings: 0

objectid
NaNs: 0, Empty strings: 0

add_full
NaNs: 0, Empty strings: 30984

addnum_pre
NaNs: 0, Empty strings: 93350

add_number
NaNs: 0, Empty strings: 2893

addnum_suf
NaNs: 0, Empty strings: 92410

st_premod
NaNs: 0, Empty strings: 93123

st_predir
NaNs: 0, Empty strings: 45147

st_pretyp
NaNs: 0, Empty strings: 83994

st_presep
NaNs: 0, Empty strings: 93361

st_name
NaNs: 0, Empty strings: 543

st_postyp
NaNs: 0, Empty strings: 12522

st_posdir
NaNs: 0, Empty strings: 86529

st_posmod
NaNs: 0, Empty strings: 93287

unit
NaNs: 0, Empty strings: 80243

floor
NaNs: 0, Empty strings: 92793

esn
NaNs: 0, Empty strings: 74596

msagcomm
NaNs: 0, Empty strings: 77967

inc_muni
NaNs: 0, Empty strings: 63091

uninc_comm
NaNs: 0, Empty strings: 88610

post_comm
NaNs: 0, Empty strings: 13945

post_code
NaNs: 0, Empty strings: 21057

county
NaNs: 0, Empty strings: 45027

placement
NaNs: 0, Empty strings: 81780

state_parcel_id
NaNs: 0, Empty strings: 61038

local_id
NaNs: 0, Empty strings: 0

nguid
NaNs: 0, Empty strings: 0

state
NaNs: 0, Empty strings: 0

source_datadesc
NaNs: 0, Empty strings: 0

source_datasetid
NaNs: 0, Empty strings: 0

source_featureid
NaNs: 0, Empty strings: 0

source_originator
NaNs: 0, Empty strings: 0

loaddate
NaNs: 0, Empty strings: 0

county_fips
NaNs: 0, Empty strings: 0

county_id
NaNs: 0, Empty strings: 0

esri_zip
NaNs: 0, Empty strings: 0

esri_poname
NaNs: 0, Empty strings: 0

dlgf_prop_address
NaNs: 0, Empty strings: 34

dlgf_prop_address_city
NaNs: 0, Empty strings: 938

dlgf_prop_address_zip
NaNs: 0, Empty strings: 267

dlgf_prop_class_code
NaNs: 0, Empty strings: 0

join_state_parcel_id
NaNs: 0, Empty strings: 0

latitude
NaNs: 0, Empty strings: 0

longitude
NaNs: 0, Empty strings: 0

orig_addr
NaNs: 0, Empty strings: 1145

geofulladdress
NaNs: 0, Empty strings: 103

geohousenum
NaNs: 0, Empty strings: 3066

geopredir
NaNs: 0, Empty strings: 45147

geopretype
NaNs: 0, Empty strings: 84035

geostreetname
NaNs: 0, Empty strings: 543

geostreettype
NaNs: 0, Empty strings: 12522

geounit
NaNs: 0, Empty strings: 80285

geocity
NaNs: 0, Empty strings: 0

geozip
NaNs: 0, Empty strings: 0

geostate
NaNs: 0, Empty strings: 0

geobg10
NaNs: 0, Empty strings: 0

geobg20
NaNs: 0, Empty strings: 0

geocounty
NaNs: 0, Empty strings: 0

geosufdir
NaNs: 0, Empty strings: 86540

user_fld
NaNs: 0, Empty strings: 0

## Select Columns

In [19]:
df_locations_selected = df_locations[[
    "location_id", 
    "dlgf_prop_class_code",
    "latitude", 
    "longitude", 
    "dlgf_prop_address", 
    "dlgf_prop_address_city",
    "dlgf_prop_address_zip",
    "geofulladdress",
    "geocity",
    "geozip",
    "geostate",
    "geobg10",
    "geobg20",
    "geocounty"
]]

df_locations_selected

,location_id,dlgf_prop_class_code,latitude,longitude,dlgf_prop_address,dlgf_prop_address_city,dlgf_prop_address_zip,geofulladdress,geocity,geozip,geostate,geobg10,geobg20,geocounty
0,54,680,40.831414,-84.927791,216 N 5TH ST,DECATUR,46733-0000,216 N FIFTH ST,DECATUR,46733,IN,180010303003.0,180010303003.0,ADAMS
1,85,680,40.668663,-84.948219,1100 SWISS WAY,BERNE,46711-0000,1200 SWISSWAY RD,DECATUR,46711,IN,180010306002.0,180010306002.0,ADAMS
2,96,610,40.744444,-84.955205,30 S US HIGHWAY 27,MONROE,46772-0000,30 UNITED STATES HIGHWAY 27,DECATUR,46772,IN,180010305001.0,180010305001.0,ADAMS
3,97,685,40.590147,-84.959463,235 DECATUR ST,GENEVA,46740-0000,225 DECATUR ST,DECATUR,46740,IN,180010307004.0,180010307004.0,ADAMS
4,126,690,40.828553,-84.945054,1824 W MONROE ST,DECATUR,46733-0000,1828 W MONROE ST,DECATUR,46733,IN,180010302002.0,180010302002.0,ADAMS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93361,3291004,699,39.239337,-86.625291,6151 N MATTHEWS DR,,,6151 N MATTHEWS DR UNIT 410,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE
93362,3291005,699,39.239337,-86.625291,6151 N MATTHEWS DR,,,6151 N MATTHEWS DR UNIT 411,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE
93363,3291287,640,39.227452,-86.617584,4616 N CAMPBELL'S PARK RD,,,4616 N CAMPBELL PARK RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013043.0,MONROE
93364,3291288,640,39.224624,-86.614133,4616 N CAMPBELL'S PARK RD,,,4586 N HARTSTRAIT RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013051.0,MONROE
93365,3291335,640,39.222248,-86.633656,4810 N ANGELA WAY,,,4810 N ANGELA WAY,BLOOMINGTON,47404,IN,181050013041.0,181050013041.0,MONROE

In [23]:
df_locations_selected.drop_duplicates(subset = ["latitude", "longitude"])

,location_id,dlgf_prop_class_code,latitude,longitude,dlgf_prop_address,dlgf_prop_address_city,dlgf_prop_address_zip,geofulladdress,geocity,geozip,geostate,geobg10,geobg20,geocounty
0,54,680,40.831414,-84.927791,216 N 5TH ST,DECATUR,46733-0000,216 N FIFTH ST,DECATUR,46733,IN,180010303003.0,180010303003.0,ADAMS
1,85,680,40.668663,-84.948219,1100 SWISS WAY,BERNE,46711-0000,1200 SWISSWAY RD,DECATUR,46711,IN,180010306002.0,180010306002.0,ADAMS
2,96,610,40.744444,-84.955205,30 S US HIGHWAY 27,MONROE,46772-0000,30 UNITED STATES HIGHWAY 27,DECATUR,46772,IN,180010305001.0,180010305001.0,ADAMS
3,97,685,40.590147,-84.959463,235 DECATUR ST,GENEVA,46740-0000,225 DECATUR ST,DECATUR,46740,IN,180010307004.0,180010307004.0,ADAMS
4,126,690,40.828553,-84.945054,1824 W MONROE ST,DECATUR,46733-0000,1828 W MONROE ST,DECATUR,46733,IN,180010302002.0,180010302002.0,ADAMS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93311,3290737,640,39.230415,-86.618630,4616 N CAMPBELL'S PARK RD,,,301 E VINE ST,ELLETTSVILLE,47429,IN,181050013032.0,181050013032.0,MONROE
93312,3290955,650,39.234818,-86.634091,601 S EDGEWOOD DR,,,550 S EDGEWOOD DR,ELLETTSVILLE,47429,IN,181050013042.0,181050013042.0,MONROE
93363,3291287,640,39.227452,-86.617584,4616 N CAMPBELL'S PARK RD,,,4616 N CAMPBELL PARK RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013043.0,MONROE
93364,3291288,640,39.224624,-86.614133,4616 N CAMPBELL'S PARK RD,,,4586 N HARTSTRAIT RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013051.0,MONROE
93365,3291335,640,39.222248,-86.633656,4810 N ANGELA WAY,,,4810 N ANGELA WAY,BLOOMINGTON,47404,IN,181050013041.0,181050013041.0,MONROE

## Column Comparison

In [20]:
df_locations_selected[df_locations_selected["dlgf_prop_address"] != df_locations_selected["geofulladdress"]]

,location_id,dlgf_prop_class_code,latitude,longitude,dlgf_prop_address,dlgf_prop_address_city,dlgf_prop_address_zip,geofulladdress,geocity,geozip,geostate,geobg10,geobg20,geocounty
0,54,680,40.831414,-84.927791,216 N 5TH ST,DECATUR,46733-0000,216 N FIFTH ST,DECATUR,46733,IN,180010303003.0,180010303003.0,ADAMS
1,85,680,40.668663,-84.948219,1100 SWISS WAY,BERNE,46711-0000,1200 SWISSWAY RD,DECATUR,46711,IN,180010306002.0,180010306002.0,ADAMS
2,96,610,40.744444,-84.955205,30 S US HIGHWAY 27,MONROE,46772-0000,30 UNITED STATES HIGHWAY 27,DECATUR,46772,IN,180010305001.0,180010305001.0,ADAMS
3,97,685,40.590147,-84.959463,235 DECATUR ST,GENEVA,46740-0000,225 DECATUR ST,DECATUR,46740,IN,180010307004.0,180010307004.0,ADAMS
4,126,690,40.828553,-84.945054,1824 W MONROE ST,DECATUR,46733-0000,1828 W MONROE ST,DECATUR,46733,IN,180010302002.0,180010302002.0,ADAMS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93360,3291003,699,39.239337,-86.625291,6151 N MATTHEWS DR,,,6151 N MATTHEWS DR UNIT 409,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE
93361,3291004,699,39.239337,-86.625291,6151 N MATTHEWS DR,,,6151 N MATTHEWS DR UNIT 410,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE
93362,3291005,699,39.239337,-86.625291,6151 N MATTHEWS DR,,,6151 N MATTHEWS DR UNIT 411,ELLETTSVILLE,47429,IN,181050013031.0,181050013031.0,MONROE
93363,3291287,640,39.227452,-86.617584,4616 N CAMPBELL'S PARK RD,,,4616 N CAMPBELL PARK RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013043.0,MONROE
93364,3291288,640,39.224624,-86.614133,4616 N CAMPBELL'S PARK RD,,,4586 N HARTSTRAIT RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013051.0,MONROE

In [22]:
df_locations_selected[df_locations_selected["geobg10"] != df_locations_selected["geobg20"]]

,location_id,dlgf_prop_class_code,latitude,longitude,dlgf_prop_address,dlgf_prop_address_city,dlgf_prop_address_zip,geofulladdress,geocity,geozip,geostate,geobg10,geobg20,geocounty
133,2962,680,40.810498,-84.916680,1703 HIGH ST,DECATUR,46733-0000,1619 HIGH ST,DECATUR,46733,IN,180010303005.0,180010303006.0,ADAMS
286,7452,685,40.592243,-84.957638,415 E LINE ST,GENEVA,46740-0000,417 E LINE ST,DECATUR,46740,IN,180010307004.0,180010307003.0,ADAMS
287,7453,685,40.592244,-84.957680,415 E LINE ST,GENEVA,46740-0000,415 E LINE ST,DECATUR,46740,IN,180010307004.0,180010307003.0,ADAMS
296,7597,640,40.592408,-84.957939,105 HIGH ST,GENEVA,46740-0000,105 HIGH ST,DECATUR,46740,IN,180010307004.0,180010307003.0,ADAMS
298,7690,680,40.592307,-84.961406,105 W LINE ST,GENEVA,46740-0000,105 W LINE ST,GENEVA,46740,IN,180010307004.0,180010307003.0,ADAMS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93130,3287322,680,39.312795,-86.627884,9195 N BOTTOM RD,ELLETTSVILLE,47429-0000,9195 N BOTTOM RD,ELLETTSVILLE,47429,IN,181050013011.0,181050013014.0,MONROE
93131,3287354,630,39.164173,-86.606234,352 S FIELDSTONE BLVD,BLOOMINGTON,47404-0000,352 S FIELDSTONE BLVD,BLOOMINGTON,47404,IN,181050005013.0,181050005012.0,MONROE
93132,3287420,685,39.209808,-86.618721,6287 W RATLIFF RD,,,6287 W RATLIFF RD,BLOOMINGTON,47404,IN,181050013014.0,181050013013.0,MONROE
93213,3288096,640,39.264978,-86.626904,7568 N RED HILL RD,,,7568 N RED HILL RD,ELLETTSVILLE,47429,IN,181050013011.0,181050013015.0,MONROE
93364,3291288,640,39.224624,-86.614133,4616 N CAMPBELL'S PARK RD,,,4586 N HARTSTRAIT RD,ELLETTSVILLE,47429,IN,181050013043.0,181050013051.0,MONROE

# Google Solar API

In [38]:
def get_solar_data(api_key, latitude, longitude):
    api_url = f"https://solar.googleapis.com/v1/buildingInsights:findClosest?location.latitude={latitude}&location.longitude={longitude}&requiredQuality=HIGH&key={api_key}"
    response = requests.get(api_url)
    solar_data = response.json()
    if response.status_code != 200:
        print(f"Error fetching data: {response.status_code}")
    else:
        print("Data fetched successfully")
        with open(f"solar_data_{latitude}_{longitude}.json", "w") as f:
            json.dump(solar_data, f, indent=4)
        return solar_data

def process_solar_data(solar_data):
    max_panel_count = solar_data["solarPotential"]["solarPanelConfigs"][-1]["panelsCount"]
    yearly_energy_production = solar_data["solarPotential"]["solarPanelConfigs"][-1]["yearlyEnergyDcKwh"]
    return max_panel_count, yearly_energy_production

In [37]:
get_solar_data("AIzaSyBgky1gbEbgW85w-_IyBA3p-RH1s4r9M0w", 41.018635, -85.167521)

<Response [400]>
Error fetching data: 400